name: Build-SDK 24.04
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Vulkan SDK version (e.g., 1.4.304.0)'
        required: false
        default: 'latest'

jobs:
  build-linux-arm:
    name: Build SDK for Linux 24.04 arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set version variable
        id: vars
        run: |
          if [[ "${{ github.event.inputs.version }}" == "latest" || -z "${{ github.event.inputs.version }}" ]]; then
            echo "SDK_URL=https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.xz" >> $GITHUB_ENV
            echo "Using default SDK version: latest"
          else
            echo "SDK_URL=https://sdk.lunarg.com/sdk/download/${{ github.event.inputs.version }}/linux/vulkansdk-linux-x86_64-${{ github.event.inputs.version }}.tar.xz" >> $GITHUB_ENV
            echo "Using specified SDK version: ${{ github.event.inputs.version }}"
          fi

      - name: Update APT
        run: sudo apt update

      - name: Install Host Dependencies
        run: sudo apt install cmake ninja-build gcc-14 g++-14 bison ocaml-core xz-utils pkg-config python3-pip -y

      - name: Install Python
        run: pip3 install setuptools wheel

      - name: Install Target Dependencies
        run: |
          sudo apt install libglm-dev libxcb-dri3-0 libxcb-present0 libpciaccess0 \
          libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev \
          libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
          libx11-xcb-dev liblz4-dev libzstd-dev \
          libxml2-dev wayland-protocols -y --no-install-recommends

      - name: Download SDK
        run: curl -L -o vulkan-sdk.tar.xz "$SDK_URL"

      - name: Extract version from tarball (if latest)
        if: github.event.inputs.version == 'latest'
        run: |
          tar -xf vulkan-sdk.tar.xz --wildcards '*/vulkansdk'
          SDK_VERSION=$(find . -maxdepth 1 -type d -name '1.*' | head -n 1 | xargs basename)
          echo "SDK_VERSION=${SDK_VERSION}" >> $GITHUB_ENV

      - name: Set version for specific releases
        if: github.event.inputs.version != 'latest'
        run: |
          echo "SDK_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Unpack SDK
        run: tar -xJf vulkan-sdk.tar.xz

      - name: Remove x86_64 directory
        run: |
          cd "$SDK_VERSION"
          rm -rf x86_64

      - name: Build SDK
        run: |
          cd "$SDK_VERSION"
          CC=/usr/bin/aarch64-linux-gnu-gcc-14 CXX=/usr/bin/aarch64-linux-gnu-g++-14 ./vulkansdk --maxjobs vulkan-loader vulkan-validationlayers vulkan-extensionlayer

      - name: Package SDK as tar.xz
        run: |
          tar -cJf "vulkansdk-linux-arm64-$SDK_VERSION.tar.xz" "$SDK_VERSION"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulkan-sdk-arm64
          path: vulkansdk-linux-arm64-${{ env.SDK_VERSION }}.tar.xz
          compression-level: 0
